name: Build and Test
permissions: read-all
on:
  schedule:
    # Every week on Sunday at 1 AM
    - cron: '0 1 * * 0'
jobs:
  build-and-test:
    runs-on:
      labels: ubuntu-20.04-16core
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: "Run `bazel build`"
        run: |
          bazel build //...

      - name: "Run `bazel test`"
        run: |
          bazel test \
            --test_output=errors \
            --test_size_filters=medium,large \
            --test_timeout=3600 \
            --experimental_ui_max_stdouterr_bytes=10485760 \
            //...
